///////////////////////////////////////////////////////////
//  CCaptainBakuba.as
//  Macromedia ActionScript Implementation of the Class CCaptainBakuba
//  Generated by Enterprise Architect
//  Created on:      14-Dec-2010 3:02:06 PM
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.ai.AIState;
	import com.game.CPlayerTeelos;
	import com.greensock.TweenMax;
	import flash.display.DisplayObjectContainer;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 14-Dec-2010 3:02:06 PM
	 */
	public class CCaptainBakuba_Clone extends CPlayerCaptain implements IRangeAttacker
	{
		private var cloneDuration:int
		private var cloneDelay:int;
		
		public function CCaptainBakuba_Clone(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_baseAttack = 2;
			m_defense = 5;
			m_maxLife = 10;
			m_unitClass = UNITCLASS.ARCHER;
			m_counterClass = UNITCLASS.INFANTRY;
			m_counterBonus = 1;
			m_baseSpeed = 0.9;
			m_baseCooldownTime = 1800;
			m_trainCost = 180;
		}
		
		override public function onCreate(lane:int, targetPosX:int, container:DisplayObjectContainer):void 
		{
			super.onCreate(lane, targetPosX, container);
			setCurrentFrame(7);
			TweenMax.killTweensOf( m_sprite );
			TweenMax.to( m_sprite, 0.2, { colorMatrixFilter: { colorize:0x0066ff, amount:0.7 }} );
			
			m_attackRange = 700;
			
			cloneDuration = 7000;
			m_cloneTimeMax = cloneDuration;
			m_cloneTimeCurr = 0;
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			m_sprite = new mcCaptain_Bakuba();
			
		}
		
		override public function update(elapsedTime:int):void 
		{
			super.update(elapsedTime);
			if (!m_cloneActive)
			{
				if (isAnimationComplete())
				{
					setInactive();
					State_GameLoop.getInstance().state = State_GameLoop.getInstance().stateDefault;
				}
			}
			else 
			{
				if ( isAnimationComplete() )
				{
					setCurrentFrame(1);
				}
			}
		}
		
		override public function releaseProjectile():void
		{
			super.releaseProjectile();
			MissileManager.getInstance().launch( CMissileArrow_Feela, m_container, m_sprite.x, m_sprite.y - 45, 
												 m_sprite.scaleX, getFaction(), m_lane,
												 m_baseAttack, m_counterClass, m_counterBonus, m_level, m_detectInvisible, this );
		}
	}//end CCaptainBakuba_Clone

}