///////////////////////////////////////////////////////////
//  CTeeloUztan.as
//  Macromedia ActionScript Implementation of the Class CTeeloUztan
//  Generated by Enterprise Architect
//  Created on:      11-Des-2010 22:25:05
//  Original author: poof!
///////////////////////////////////////////////////////////

package com.game
{
	import com.game.ai.AIState;
	import com.game.CEnemyTeelos;
	import flash.display.DisplayObjectContainer;

	/**
	 * @author poof!
	 * @version 1.0
	 * @created 11-Des-2010 22:25:05
	 */
	public class CTeeloKapitro extends CEnemyTeelos implements IHybridAttacker
	{
		public function CTeeloKapitro(){

		}
		
		override public function initialize():void 
		{
			super.initialize();
			
			m_baseAttack = 5;
			m_baseRangeAttack = 3;
			m_defense = 1;
			m_maxLife = 30;
			m_unitClass = UNITCLASS.HYBRID;
			m_counterClass = UNITCLASS.NONE;
			m_counterBonus = 0;
			m_baseSpeed = 0.04;
			m_dropMin = 0; //siom, 23jan011 12:28
			m_dropMax = 3;
			m_baseCooldownTime = 1200;
		}
		
		override public function onCreate(lane:int, xPos:int, container:DisplayObjectContainer):void 
		{
			super.onCreate(lane, xPos, container);
			m_attackRange = 300;
		}
		
		override protected function createSprite():void 
		{
			super.createSprite();
			//m_sprite = new mc_EnemyKapitro();
		}
		
		override public function releaseProjectile():void 
		{
			super.releaseProjectile();
			MissileManager.getInstance().launch( CMissileArrow_Croztan, m_container, m_sprite.x, m_sprite.y - 45, 
												 m_sprite.scaleX, getFaction(), m_lane,
												 m_baseAttack, m_counterClass, m_counterBonus, m_level, m_detectInvisible, this );
		}
	}//end CTeeloKapitro
}